import{a as b,S as v,i as n}from"./assets/vendor-xwsNXkQR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const P="52826967-21134cff4c4a1edd285b3f00c";async function u(s,r){try{return(await b.get("https://pixabay.com/api/",{params:{key:P,q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(e){throw e}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),S=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function g(s){const r=s.map(e=>`<li class="gallery-list">
        <a class="gallery-link" href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"  class="image-list"/>
        <div class="image-info">
        
        <p><span>Likes</span> ${e.likes} </p>
        <p><span>Views</span> ${e.views} </p>
        <p><span>Comments</span> ${e.comments} </p>
        <p><span>Downloads</span> ${e.downloads} </p>
        </div></a></li>
        `).join("");p.insertAdjacentHTML("beforeend",r),S.refresh()}function h(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function q(){p.innerHTML=""}function l(){m.classList.add("hidden-load-more")}function L(){m.classList.remove("hidden-load-more")}const E=document.querySelector(".form"),M=document.querySelector(".load-more");M.addEventListener("click",$);E.addEventListener("submit",R);let i=1,w="",d=0;l();async function R(s){s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){n.error({title:"Error",message:"Please enter a search word!",position:"topRight"});return}w=r,i=1,q(),l(),h();try{const e=await u(r,i),a=e.hits;if(d=e.totalHits,!a||a.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(a),i*15<d?L():(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.log("error",e),console.log("error",e.message),n.error({title:"Error",message:"Failed to fetch images. Try again!",position:"topRight"})}finally{y()}}async function $(){h(),i++,l();try{const r=(await u(w,i)).hits;g(r);const{height:e}=document.querySelector(".gallery-list").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"});const t=Math.ceil(d/15);i>=t?(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L()}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
